language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
          env: COMPILER=g++-8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - clang-6.0
          env: COMPILER=clang++-6.0

notification:
  email: false

befor_install:
- sudo apt-get update -qq

install:
- sudo apt-get install -qq  qt5-default qtbase5-dev lcov

script:
- mkdir build && cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make -j4
- cd tests
- ./normal_tests
- cd ..
